# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx1024m
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:b8:4a:86:da:b3:7f:35:f5:62:68:61:d6:29:8b:ac"
      - checkout
      - run:
           name: Install JDK 11
           command: |
                  sudo add-apt-repository ppa:openjdk-r/ppa;
                  sudo apt-get update -q;
                  sudo apt install -y openjdk-11-jdk-headless
           when: always
      - run:
          name: Run build with tests
          command:  if [[ -z "$GIT_USER_EMAIL" ]]; then  mvn clean  install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true;fi
      - run:
           name: Save test results
           command: |
                  mkdir -p ~/junit/
                  find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
                  bash <(curl -s https://codecov.io/bash)
           when: always
      - store_test_results:
            path: ~/junit
      - store_artifacts:
            path: ~/junit
      - run:
            name: Save artifacts
            command: |
                    mkdir -p ~/artifacts/
                    find . -type f -regex ".*/target/.*jar" -exec cp {} ~/artifacts/ \;
            when: always
      - store_test_results:
            path: ~/artifacts
      - store_artifacts:
            path: ~/artifacts
